first task
IgorShal/OOP pull request #1
Opened 2023-09-13 04:32 UTC by IgorShal

2023-09-14 14:13 UTC, galinabykova requested changes

2023-09-14 14:13 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +        int mx = i;
здесь и далее хотелось бы более понятное название, сейчас непонятно, что это за функция

2023-09-14 14:13 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +            heapify(arr, length, mx);
почему рекурсию надо использовать осторожно?

2023-09-14 14:13 UTC, galinabykova commented on Task_1_1_1/src/test/java/SampleTest.java
При тестировании принято проверять краевые случаи, так как на них часто делаются ошибки. Добавь такие тесты. Также хотелось бы, чтобы были тесты с разным числом элементов в массиве

2023-09-14 14:13 UTC, galinabykova commented on Task_1_1_1/src/test/java/SampleTest.java
> +    void test1() {
тестам надо давать осмысленные названия, чтобы сразу было видно, какая функциональность поломана

2023-09-18 12:20 UTC, IgorShal commented
Всё исправил, рекурсию надо использовать осторожно, чтобы не попасть в бесконечную рекурсию, которая может заполнить стек

2023-09-18 12:21 UTC, IgorShal commented
Поменял рекурсию на цикл

2023-09-18 15:01 UTC, galinabykova requested changes
исправь ошибки reviewdog и дай более длинные имена переменным (мне непонятно, что значит сокращение mx)

2023-09-18 15:41 UTC, galinabykova requested changes

2023-09-18 15:41 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static String heapsort(int[] arr) {
а почему ты тут решил возвращать строку?

2023-09-18 15:41 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static void main(String[] args) {
хотелось бы, чтобы программа ещё что-то выводила в stdout

2023-09-18 17:25 UTC, galinabykova requested changes
оставила замечания

2023-09-19 02:55 UTC, IgorShal commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static String heapsort(int[] arr) {
По условию задачи подумал, что у нас программа должна на вход получать массив интов Вход heapsort(new int[] {5, 4, 3, 2, 1}); а на выход возвращать строку с массивом в форме Выход [1, 2, 3, 4, 5]. И когда только писал, не знал, как работают тесты. А в си у нас все массивы надо было вот так печатать в тестах

2023-09-19 02:55 UTC, IgorShal commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static String heapsort(int[] arr) {
Короче говоря, подумал, что тут тесты, как у нас в Си были

2023-09-19 02:56 UTC, IgorShal commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static String heapsort(int[] arr) {
Но можно и просто отсортированный массив возвращать)

2023-09-19 03:06 UTC, IgorShal commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static void main(String[] args) {
Исправил

2023-09-19 04:21 UTC, galinabykova requested changes

2023-09-19 04:21 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.java
> +    public static String heapsort(int[] arr) {
сделай просто отсортированный массив)

2023-09-19 08:55 UTC, IgorShal commented
Изменил, теперь функция сортировки возвращает новый массив, но уже отсортированный

2023-09-19 08:59 UTC, galinabykova requested changes
у тебя покрытие теперь меньше, чем надо, его тоже нужно исправить

2023-09-19 17:40 UTC, galinabykova approved these changes
на защите надо будет рассказать общую идею пирамидальной сортировки и запустить main

2023-09-20 17:38 UTC, merged