Task_2_1_1
IgorShal/OOP pull request #11
Opened 2024-02-11 11:34 UTC by IgorShal

2024-02-12 07:55 UTC, galinabykova requested changes
reviewdog, график и в следующий раз называй пакет осмысленно

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/SequentualSolver.java
> +        }
мне кажется, можно обойтись без этой ветки

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +        }
если я ничего не напутала, то тут такая же реализация, как и в других решателях. Лучше сделать одну, три раза дублировать один и тот же код - плохо. Можно сделать дефолтный метод в интерфейсе или как-то ещё от этого избавиться

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/SequentualSolver.java
> +        return false;
тут можно использовать StreamAPI

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelStreamSolver.java
> +        return Arrays.stream(arr).parallel().mapToObj(this::isPrime).anyMatch(x -> !x);
как вариант тут можно было сделать filter по условию, а потом проверить, пустой стрим или нет. Менять не надо, просто подумала, что надо написать)

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    answer = true;
может ли тут случиться гонка ресурсов?

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
прикольное решение. Мне больше нравится вариант с параметризованными тестами, потому что он там автоматически названия тестам ещё делает, но у тебя это прикольно сделано. Не задумывалась, что так можно

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    answer = true;
и не нужен ли тут volatile?

2024-02-12 07:55 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
зачем нужен этот блок?

2024-02-15 08:53 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/SequentualSolver.java
> +        }
Согласен

2024-02-15 08:54 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +        }
Не знал, что есть default у интерфейсов, отличная идея,спасибо))

2024-02-15 09:14 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/SequentualSolver.java
> +        return false;
Хорошо)

2024-02-15 09:15 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelStreamSolver.java
> +        return Arrays.stream(arr).parallel().mapToObj(this::isPrime).anyMatch(x -> !x);
Хорошая идея

2024-02-15 09:21 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    answer = true;
Изначально хотел ответить, что гонки быть не должно, так как у нас используется общая для всех потоков переменная, изменение которой мы видим во всех потоков. Но на самом деле, если значение этой переменной кешировалось в нить, то поток не увидит её изменение. Поэтому надо использовать volatile

2024-02-15 09:24 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    answer = true;
Гонки здесь действительно нет, но работать может неверно из-за кэширования. Всё верно)

2024-02-15 09:27 UTC, IgorShal commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
В первый раз слышу про параметризированные тесты. Может они в прошлом семестре были, не помню, если честно. Прочитаю про них, спасибо)

2024-02-15 09:28 UTC, IgorShal commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
Думаю, они сильно упростят код)

2024-02-15 09:31 UTC, galinabykova commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
мне нравится вот эта статейка
https://habr.com/ru/articles/591007/
я её всю не прочла, читать сложно, но можно быстро полистать, чтобы найти нужную фичу параметризованных тестов

2024-02-15 09:32 UTC, galinabykova commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
можешь ещё посмотреть, как я их писала в примере из семинара

https://github.com/galinabykova/ExampleThreads/blob/Task_2_1_1/src/test/java/ru/nsu/bykova/PalindromeDetectorTest.java

2024-02-15 09:35 UTC, IgorShal commented on Task_2_1_1/src/test/java/PrimeSolversTest.java
> +    ArrayList<Solver> solvers;
Спасибо

2024-02-15 09:39 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
Ну вообще, в этом блоке я жду пока все задачи для пула нитей выполнятся, это будет означать, что все числа из массива будут проверены на простоту, потому что мы не можем дать ответ, есть ли непростое число в массиве, если все проверенные числа - простые, а остальные мы ещё не проверили, отсюда надо ждать завершения

2024-02-15 09:41 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
С другой стороны, нам не нужно ждать, если мы уже нашли одно непростое, поэтому я добавил костыль с переменной answer, которая, если мы нашли непростое, позволяет не проверять простоту остальных чисел, и нить с заданием на проверку простоты сразу возвращает фолз

2024-02-15 09:44 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
Так-то в таком случае нам не надо ждать завершения нитей, и этот блок, казалось бы, не нужен, но вроде может возникнуть ситуация, когда программа уже завершилась, а какая-то нить всё ещё проверяет какой-нибудь лонг на простоту

2024-02-15 10:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
кажется, в случае, когда какая-нибудь нить будет проверять long на простоту, это не сильно поможет. Судя по документации
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#shutdownNow--
тут мы делаем interrupt нити, но этот метод не останавливает нить:
https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupt--

2024-02-17 12:03 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
Согласен, этот блок тут не нужен

2024-02-17 12:37 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
В общем, я немного переделал решение, раньше я использовал invokeAll, который добавляет все задания в executor service и ждёт их завершения. Но, поскольку, как я писал выше, нам не нужны задания, если мы уже нашли непростое, я убрал этот метод  и теперь добавляю задания все по одному, но, если мы нашли непростое, я через shotdownNow закрываю приём задания es,останавливаю выполнение всех задач и возвращаю true. В теории решение должно ускориться, на практике скорость та же(

2024-02-17 12:38 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            }
А ну ещё в таком случае не нужен костыль с answer

2024-02-17 15:53 UTC, galinabykova requested changes

2024-02-17 15:53 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +    private volatile boolean answer = false;
я немного наврала всем про volatile. В вашем случае его можно было не использовать, из-за того, что join даёт гарантии happens-before
Если бы у тебя поток не завершался, он бы был нужен, а join даёт нужную гарантию
https://docs.oracle.com/javase/tutorial/essential/concurrency/memconsist.html

Но у тебя эта переменная больше не используется, так что её, наверно, можно полностью убрать)

2024-02-17 15:53 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
вот тут, мне кажется, можно использовать StreamAPI. В другом месте, я бы, может, не стала просить переделать, но тут метод много последовательных действий делает, если будет меньше строчек, будет удобнее (на экран больше последовательных действий влезет)

2024-02-17 15:53 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
с помощью map

2024-02-17 15:53 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    es.shutdownNow();
изменится ли поведение программы, если здесь написать
`es.shutdown();` вместо Now
(исправлять не надо, просто вопрос)?

2024-02-18 10:40 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +    private volatile boolean answer = false;
Понял, спасибо)

2024-02-19 10:25 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
Добавил.

2024-02-19 10:31 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    es.shutdownNow();
В теории да, тут я поставил именно Now, чтобы в случае длинного лонга простого он прекращал его вычисление сразу, не досчитывая, а если поменять на обычный шотдаун, он подождёт, пока лонг досчитается, а потом уже вернёт ответ.

2024-02-19 10:34 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
Криво получилось, конечно, в основном из-за того, что ,оказывается, стримы ленивые.

2024-02-19 10:35 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
Я этого не знал и удивлялся, когда исключения кидались в конце программы, а не там, где я их обрабатываю.

2024-02-19 11:43 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
стримы ленивые, но я collect терминальная операция, поэтому на ней, по идее всё должно было вычислиться. Я, наверно, криво сформулировала, я имела ввиду сделать просто такое изменение
![image](https://github.com/IgorShal/OOP/assets/86754545/33300892-82ad-4d81-a865-74d10eedb9e2)

2024-02-19 11:43 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
криво сформулировала(

2024-02-19 11:46 UTC, galinabykova commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    es.shutdownNow();
Now действительно работает так, но тут есть особенность, связанная с самим процессом прерывания потока. Interrupt в java не останавливает поток, а лишь выставляет статус, который поток должен проверять. 
https://download.java.net/java/early_access/valhalla/docs/api/java.base/java/lang/Thread.html#interrupt()
https://download.java.net/java/early_access/valhalla/docs/api/java.base/java/lang/Thread.html#interrupted()

2024-02-19 11:47 UTC, galinabykova approved these changes
посмотри ещё ответы на прошлые комментарии)

2024-02-19 14:06 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +            tasks.add(new PrimeTask(num));
А, я так и хотел сделать, но потом подумал, а почему бы всё вообще на стримах не переписать))

2024-02-19 14:07 UTC, IgorShal commented on Task_2_1_1/src/main/java/org/example/ParallelSolver.java
> +                    es.shutdownNow();
Прочитаю, спасибо

2024-02-23 12:48 UTC, merged