Task_2_1_2
IgorShal/OOP pull request #12
Opened 2024-03-08 14:05 UTC by IgorShal

2024-03-08 14:11 UTC, IgorShal commented
Пока не добавил поиск воркеров через броадкаст, так как только вчера узнал, что его нужно добавить(

2024-03-08 14:29 UTC, IgorShal commented
Глобальная идея очень простая: есть пользователь с массивом чисел и намерением узнать, есть ли в массиве непростые числа, он также является сервером, к нему подключаются другие пользователи, каждый из них получает часть массива и выдаёт ответ, сервер собирает ответы и выдает результат

2024-03-08 14:30 UTC, IgorShal commented
Также добавил возможность подключения многопоточности для решения задачи, то есть можно использовать в качестве рабочих как потоки, так и других пользователей

2024-03-08 14:30 UTC, IgorShal commented
Сам же сервер ничего не делает кроме как раздачи задач и получения ответов, то есть он не проверяет ничего на простоту

2024-03-08 14:32 UTC, IgorShal commented
Ну и сам сервер сделал через мультиплексирование, то есть использовал Selector, а поэтому вместо сокетов я везде использую каналы

2024-03-12 19:18 UTC, galinabykova reviewed
Мне не нравится, что у тебя смешаны всякие сериализации/десериализации и какие-то сетевые действия. Если будут вноситься изменения в протокол, нужно будет найти место сначала с сериализацией, потом с десериализацией, и для того и для другого нужно будет лезть в кишки классов, отвечающих за сетевое взаимодействие. Лучше вынести эту логику в отдельные сущности

2024-03-12 19:18 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/example/Client.java
> +package org.example;
переименуй пожалуйста, пакет

2024-03-12 19:20 UTC, galinabykova reviewed
ещё сделай, пожалуйста, точки входа для клиента и сервера, чтобы их можно было запускать

2024-03-12 19:35 UTC, galinabykova requested changes
у тебя получилось лаконичное решение) Нужно ещё сделать поиск в подсети

2024-03-12 19:35 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/example/Server.java
> +            for (SelectionKey key : selectedKeys) {
мне кажется, этот цикл можно сделать более читаемым (например, если перегруппировать try-catch, и сделать continue в ветке !key.isValid())

2024-03-12 19:36 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/example/Server.java
> +            for (SelectionKey key : selectedKeys) {
цикл, начинающийся на строчке 92

2024-03-23 15:51 UTC, IgorShal commented
> ещё сделай, пожалуйста, точки входа для клиента и сервера, чтобы их можно было запускать. И чтобы порт можно было в аргументах задавать

Для клиента сделал, а для сервера разве нужно, у меня же сервер является частью основной программы для решения

2024-03-23 15:51 UTC, IgorShal commented
@galinabykova Какие-то интеграционные тесты нужны или моих достаточно?

2024-03-23 15:58 UTC, IgorShal commented
Если дополнительные тесты не нужны, тогда я броадкаст добавил, щас буду рефакторинг делать

2024-03-23 16:11 UTC, galinabykova commented
> @galinabykova Какие-то интеграционные тесты нужны или моих достаточно?

хотелось бы ещё тест, где демонстрируется, что после гибели узла, его задачи будут посчитаны другими узлами (чтобы его задачи влияли на результат, например, только у него есть непростое число)

2024-03-23 16:17 UTC, galinabykova commented
> > ещё сделай, пожалуйста, точки входа для клиента и сервера, чтобы их можно было запускать. И чтобы порт можно было в аргументах задавать
> 
> Для клиента сделал, а для сервера разве нужно, у меня же сервер является частью основной программы для решения

я не точно выразилась, хочется, чтобы были все точки входа, которые нужны для запуска системы

2024-03-24 18:15 UTC, IgorShal commented
Добавил поиск через мультикаст, так как броадкаст нифига на линуксе не работает. Добавил тест для падения клиента и немного отрефакторил код

2024-03-24 18:53 UTC, galinabykova requested changes

2024-03-24 18:53 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/ClientMain.java
> +            throw new RuntimeException("No port specified");
тут можно было бы сделать что-то более дружелюбное для обычного пользователя, в stderr чего-нибудь написать и ненулевой код возврата вернуть. Я тоже люблю исключения, но непрограммиста это напугать может)

2024-03-24 18:53 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Client.java
этот класс умеет общаться по сети, сериализовать, определять, простое ли число. Мне кажется, что это нарушает принцип единственности ответственности (если нет, можешь поспорить со мной). Пожалуйста, разбей его на несколько классов

2024-03-24 18:53 UTC, galinabykova commented on Task_2_1_2/src/test/java/InetTests.java
и ещё бы юнит тестики на всякие isPrime и т.д. Можно на сериализацию было бы ещё, но это если удобно будет

2024-03-25 06:52 UTC, IgorShal commented
Добавил тест performTask, сериализации, а также убрал её из классов сервера и клиента и перенес её в отдельный класс. Так выглядит намного лучше

2024-03-25 08:23 UTC, galinabykova requested changes

2024-03-25 08:23 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +    public static InetSocketAddress getAddressByBuffer(byte[] bytes) throws UnknownHostException {
у тебя у задачи есть как сериализация, так десериализация, а тут, если я правильно поняла, ты не стал выносить сериализацию для адреса, потому что там две строчки кода. Несмотря на то, что там две строчки, мне кажется, стоит вынести, потому что это сейчас тут две строчки, но кто знает, что будет дальше, если ты будешь (предположим) поддерживать этот код?

2024-03-25 08:23 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
так как этот класс набор статических методов, тут можно сделать приватный конструктор

2024-03-25 08:23 UTC, galinabykova commented on Task_2_1_2/src/test/java/InetTests.java
Хмм. с одной стороны, мне кажется, этот класс тоже бы надо разбить на несколько, потому что ты тут вообще всё тестируешь) но с другой, ты используешь общий provideArgues... я бы сериализацию всё-таки вынесла, наверно, и продумала, какие ситуации нужно конкретно для неё протестить

2024-03-25 08:23 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
ещё непонятно, почему в этом классе нет сериализации и десериализации результата

2024-03-25 10:32 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +    public static InetSocketAddress getAddressByBuffer(byte[] bytes) throws UnknownHostException {
Согласен

2024-03-25 10:35 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
А для чего?

2024-03-25 10:35 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
Тогда этот конструктор просто ничего не будет делать

2024-03-25 10:36 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
Согласен

2024-03-25 10:36 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
Забыл совсем

2024-03-25 10:57 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
ага, это стандартный способ показать, что этот класс набор статических методов, и тебе не надо создавать его объект для работы. Например, Math такой
https://qna.habr.com/q/981293

2024-03-25 10:58 UTC, galinabykova commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
так себе источник, но мне немного лень искать исходники)

2024-03-25 12:01 UTC, IgorShal commented on Task_2_1_2/src/main/java/org/solver/Serializer.java
> +public class Serializer {
Спасибо.

2024-03-25 12:31 UTC, IgorShal commented
Всё исправил. Интересный факт : при чтении из закрытого канала на винде бросается исключение, а на линуксе возвращается -1 :D

2024-03-25 12:36 UTC, IgorShal commented
Хотя стоп, я обманщик
Это от версии jdk зависит

2024-03-25 14:20 UTC, galinabykova commented
> Хотя стоп, я обманщик Это от версии jdk зависит

О, интересно

2024-03-25 17:05 UTC, galinabykova approved these changes
по поводу \n, может быть \0 было бы логичнее, но в целом, мне кажется, норм решение

2024-03-25 17:06 UTC, IgorShal commented
> по поводу \n, может быть \0 было бы логичнее, но в целом, мне кажется, норм решение

2024-03-25 17:07 UTC, IgorShal commented
Спасибо)

2024-03-26 14:50 UTC, merged