Task_2_2_1
IgorShal/OOP pull request #13
Opened 2024-04-08 15:54 UTC by IgorShal

В общем-ссссс...
Из важного:
У курьеров своя скорость доставки.
После окончания дня курьеры доставляют все заказы которые у них есть в сумке. Пиццы, которые не успели доставиться и лежат на складе + заказы, которые не успели доделаться (например, у пиццы готовность 50 процентов может быть) сериализуются в файл pizzeria.txt и в начале следующего дня достаются. Я решил, что курьеры, которые на середине пути к клиенту разворачиваются домой, потому что время работы кончилась - идея так себе)) Зато наполовину готовая пицца - самое то!

2024-04-08 15:58 UTC, IgorShal commented
UML пока нет
JSON тоже блин(

2024-04-08 15:59 UTC, IgorShal commented
Логи вывожу в stdout, не знал, что что-то другое надо

2024-04-09 09:37 UTC, galinabykova requested changes
Для первого решения - очень хорошо) правда, у меня сложилось впечатление, что в твоей пиццерии, если в какой-то момент заказы кончатся, работники воспримут это как конец рабочего дня)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> implements Queue<T>, Serializeble {
Ооо, ты тут решил реализовать интерфейс очереди java? С одной стороны это круто, потому что можно использовать с ней какие-то стандартные алгоритмы, с другой стороны - а можешь ли? Многопоточка очень сильно влияет на возможности очереди, и, возможно, другой API был бы удобнее. Например, у тебя тут есть методы size, isEmpty и другие, которые не гарантируют, что возвращают истинные значения. Без этого знания использовать очередь нельзя, поэтому возникает вопрос с тем, насколько корректно ты реализуешь контракт очереди здесь

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> implements Queue<T>, Serializeble {
у меня сейчас идёт курс по алгоритмам во внешней памяти, и там мы как раз пришли недавно к изменению API одной из стандартных структур данных, потому что стандартное ужасно медленно во внешней памяти. Тут немного другая ситуация, но напомнило)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +    public int size() {
этот метод может врать, поэтому надо предупредить в документации об этом пользователя

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +        this.hasElements.signalAll();
тут, кажется, можно было бы будить только, когда добавили элемент в пустую очередь (но я могу ошибаться)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +                bakerArrayList.add(baker);
может вот эти две строчки 
```
Baker baker = new Baker(1000);
bakerArrayList.add(baker);
```
создавать в основном потоке? или нужно синхронизировать bakerArrayList

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Baker.java
> +    public int workingStep(Pizzeria pizzeria) {
тут лучше возвращать какую-то именнованную константу

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Baker.java
> +    public int workingStep(Pizzeria pizzeria) {
0 и 1 - магические константы в текущем решении

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Baker.java
> +        this.state = State.READY;
интересно, что у тебя эта строчка в начале и конце метода. Нужно ли это?

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Baker.java
> +        this.state = State.READY;
и ещё состояния меняются, как во внутренних методах (preparePizza, getOrder), так и тут, это странно немного)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Courier.java
> +            } catch (IndexOutOfBoundsException e) {
ты тут используешь исключения как if, проброшенные через несколько слоёв методов) мне кажется, всё таки было бы лучше возвращать Optional или просто null, когда объекта нет, и проверять его тут на empty/null. Лучше, конечно, Optional, потому что оно заставляет пользователя проверять, что тут не null. Но идея хорошая, сочетание блокирующего и неблокирующего метода для сбора сумки курьера - красивое решение)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Courier.java
> +            order.setDistanceToPlace(order.getDistanceToPlace() - 1);
фигасе, прям скорость и расстояние до места, круто)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +                throw new RuntimeException(e);
кажется, ты ловишь это исключение далее, RuntimeException здесь RuntimeException, потому что из poll ты не можешь бросать проверяемые исключения?

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +        }
а может тут просто уснуть на нужное время?)

2024-04-09 09:37 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public void makeOrder(int count) {
а можно ли после окончания рабочего дня вызвать этот метод? что при этом произойдёт?

2024-04-10 15:57 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> implements Queue<T>, Serializeble {
Я подумал; blockingQueue это же Queue, значит надо имплементить интерфейс очереди, ну а вообще хотелось бы что-то другое использовать)

2024-04-10 15:57 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +    public int size() {
Согласен

2024-04-10 15:58 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +        this.hasElements.signalAll();
Согласен

2024-04-10 16:14 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/Courier.java
> +            order.setDistanceToPlace(order.getDistanceToPlace() - 1);
Ахахах

2024-04-10 16:15 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +                throw new RuntimeException(e);
Да

2024-04-10 16:16 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +        }
Ой

2024-04-10 16:25 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public void makeOrder(int count) {
Эти заказы пропадут, сдвинется номер заказов, которые мы получим из файла. 
Например, у меня были заказы 1 2 3, они обработались
Потом мы вызвали в конце дня makeOrder 3 и он добавил в очередь заказов новые, но они потерялись во время загрузки из файла, при этом переменная максимального номера поменяется на 6

2024-04-10 16:27 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public void makeOrder(int count) {
Makeorder генерирует n заказов с номерами начиная от прошлого максимального

2024-04-10 16:28 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public void makeOrder(int count) {
В каком-нибудь Папа Карло, конечно, номера заказов каждый день обнуляются, но тут мы загружаем заказы из файла с номерами из предыдущего дня, поэтому я решил, что у меня номера заказов будут с каждым днём всё больше)

2024-04-10 16:30 UTC, IgorShal commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public void makeOrder(int count) {
Но вообще не хочется создавать новые заказы после конца дня, щас исправлю

2024-04-11 09:04 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/blockingQueue/OwnBlockingQueue.java
> +                throw new RuntimeException(e);
лучше сделать своё исключение-наследника RuntimeException, так будет понятнее)

2024-04-11 16:36 UTC, IgorShal commented
Правки внёс, добавил несколько тестов. UML диаграмму добавил, логгирование тоже, json тоже. Чуть позже займусь комментами и ревьюдогами.

2024-04-12 05:30 UTC, galinabykova requested changes
Всё хорошо, добавь комменты для документации, исправь reviewdog и всё)

2024-04-12 05:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public ArrayList<Baker> generateBakers(int bakersCount) {
кажется, что этот и несколько других методов в этом классе нужны чисто, чтобы вытащить объёмную логику из другого метода и самостоятельно не используется. Можно сделать их private

2024-04-12 05:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/org/pizzeriaSim/PizzeriaThreadsSim.java
> +    public static Logger LOGGER;
кажется, обычно стараются не использовать один логгер во всём приложении, так как в будущем могут понадобиться какие-то особенные конфигурации для логгирования какой-то части сообщений. Обычно используют один логгер на класс

2024-04-14 08:28 UTC, galinabykova approved these changes

2024-04-20 15:35 UTC, merged