Task_2_3_1
IgorShal/OOP pull request #14
Opened 2024-04-29 15:59 UTC by IgorShal

Код оставляет желать лучшего. Но всё на мягкий дедлайн есть. Ещё крутую штуку добавил: игра меняется в зависимости от размера окна.

2024-04-29 16:30 UTC, IgorShal commented
Правда с этим свзяан небольшой баг, но обещаю пофиксить в ближайшее время

2024-04-29 16:32 UTC, IgorShal commented
По идее должен билдиться, хотя и ошибку выдал. Скорее всего, ошибку выдаёт потому что у меня в принципе нет файла с тестами

2024-04-29 17:03 UTC, IgorShal commented
Пофиксил баг, теперь можно менять размер окна и смотреть, что получится

2024-04-30 05:09 UTC, galinabykova requested changes
хорошее разделение на классы бизнес-логики. Должны появиться fxml и напиши ещё, пожалуйста, какой паттерн используешь (я по коду не поняла)

2024-04-30 05:09 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/logic/Cell.java
> +    public boolean equals(Cell b){
HashCode нужно переопределить)

2024-04-30 05:09 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/logic/CoordinatesTranslator.java
> +    private CoordinatesTranslator() {
о, круто, что ты запретил создание объектов класса)

2024-04-30 05:09 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainApplication.java
> +
это всё-таки часть бизнес-логики, вынеси это хотя бы в метод в snake, который будешь тут вызывать

2024-04-30 05:09 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainApplication.java
> +            public void handle(long now) {
у тебя здесь смешана бизнес-логика и представление. Здесь ты можешь максимум вызывать методы модели, но никак не определять статус игры. Скорее всего, нужен отдельный класс для игры, где будут яблоки, змейки и т.д.

2024-04-30 07:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainApplication.java
> +            public void handle(long now) {
представь, что тебе помимо оконного интерфейса, надо будет ещё консольный пилить

2024-05-06 13:00 UTC, IgorShal commented
Много что изменил: добавил победу, поражение, менюшку, тесты логики. Код всё ещё оставляет желать лучшего, но на мой взгляд стало сильно лучше. Несмотря на наличие класса Controller, модель скорее MVVM.

2024-05-06 18:17 UTC, galinabykova requested changes
Действительно, стало значительно лучше) при использовании javafx есть штуки, которые выглядят странно, но разобраться с новой библиотекой было непросто, так что это нормально. У меня есть некоторые непонятки с тем, почему код так организован, так что, наверно, попрошу тебя при очной защите подробно описать, как у тебя реализован паттерн MVVM. Очень хотелось бы, чтобы ты немного потыкался с биндингами, хотя бы просто посмотрел, как это может быть устроено, потому что это такая штука, про которую, если не знать, можно не понять, что делаешь что-то не так при реализации UI, поэтому про неё тоже спрошу)

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
> +            if (children.get(i).getClass().getSimpleName().equals("Rectangle")) {
возможно тут можно использовать instanceof

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
> +        drawCell(apple, "#FA2A2A");
вообще обычно все цвета выносятся в отдельный файл с константами стиля, когда пишут UI. Это помогает быстро стиль менять. Но тут это я так, для общего развития

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
> +                this.pauseText.setVisible(false);
вот так обычно не делают. То, что у тебя разные сцены управляются одним классом - не очень хорошее решение, в одном файлике смешивается разная логика, это нехорошо, плюс, само существование всех ui-компонентов в течение жизни всего приложения, звучит опасненько (память всю сожрут)

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
> +        this.score.setText(((Number) newScore).toString());
а можно было score забиндить

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/logic/Game.java
> +    private int applesCount;
а это не поле модели?

2024-05-06 18:17 UTC, galinabykova commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
не совсем понимаю, как разделены MainApplication и MainController, за что отвечает каждый класс, кратко объясни, пожалуйста

2024-05-06 18:24 UTC, IgorShal commented on Task_2_3_1/src/main/java/com/snake/logic/Game.java
> +    private int applesCount;
Ну да, тоже поле)

2024-05-06 18:28 UTC, IgorShal commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
MainApplication по сути просто менеждер сцен. Решает, какая именно сцена будет отображаться + служит для связи MainController и модели. MainController - отображение + получение событий от пользователя. MainController  получает события из MainController  и передаёт модели для обработки.

2024-05-06 18:29 UTC, IgorShal commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
По сути, эти два класса вместе и являются ViewModel

2024-05-06 18:30 UTC, IgorShal commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
Ничего лучше не придумал(

2024-05-07 04:55 UTC, IgorShal commented on Task_2_3_1/src/main/java/com/snake/javafx/MainController.java
> +            if (children.get(i).getClass().getSimpleName().equals("Rectangle")) {
офигеть,  так можно

2024-05-08 04:52 UTC, IgorShal commented
Добавил биндинги, поменял немного названия папок, чтобы архитектура была чуть понятнее, добавил окошко для поражения. Пофиксил немного багов.

2024-05-08 04:55 UTC, IgorShal commented
Ну и остальные изменения внёс

2024-05-08 05:36 UTC, galinabykova requested changes
супер, остался ревьюдог на жёсткий дедлайн

2024-05-08 05:36 UTC, galinabykova commented on Task_2_3_1/src/main/resources/com/snake/viewmodel/gameEngine.fxml
это относится к view)

2024-05-08 11:00 UTC, IgorShal commented
Вроде всё. Насчёт покрытия, все методы модели протестированы.

2024-05-08 16:15 UTC, galinabykova approved these changes

2024-05-19 08:52 UTC, IgorShal commented
Здравствуйте, добавил 3 типа змеек ботов, выбор сложности для соревнования с ботом 1на1

2024-05-19 08:52 UTC, IgorShal commented
Думаю, надо ещё тесты добавить и комменты

2024-05-19 08:58 UTC, IgorShal commented
С алгоритмами пересечения тяжко было, но вроде что-то как-то работает

2024-05-19 09:34 UTC, galinabykova requested changes
Для плюс балла достаточно исправить замечания reviewdog)

у меня есть некоторые сомнения в разумности разбивки по классам ai-змеек. Кажется, что вероятность выбора лучшего направления можно было параметризировать одним параметром, а не делать для этого несколько классов со схожим кодом. Ещё можно было сделать разные стратегии за счёт выбора цели. 

Также есть подозрение, что AiSnake можно было бы сделать интерфейсом, а методы, которые там есть, вынести куда-то в новое место. Абстрактный класс, по моему мнению, логично использовать, если у тебя есть публичный метод, и в нём нужно вызвать другой метод, который будет отличаться в наследниках. У тебя же публичный метод определяется наследником, а AiSnake просто предоставляет полезные для расчёта методы.

Но я думаю, что ты всё это знаешь, просто из-за нехватки времени сделал так, как сделал, так что не буду требовать переделать)

2024-05-19 09:52 UTC, IgorShal commented
Про разные классы согласен, сначала именно разные стратегии и хотел сделать, потом передумал, а разбиение на классы осталось)

2024-05-19 09:54 UTC, IgorShal commented
Вообще у меня всё 100500 раз менялось и вырезалось, поэтому итоговое решение неособо красивое(

2024-05-19 09:59 UTC, IgorShal commented
Очень тяжело архитектуру продумывать, вроде приходит крутая идея, а пока пытаешься её реализовать, приходиться вставлять всё новые и новые костыли, в итоге получается фигня.

2024-05-19 12:33 UTC, IgorShal commented
Исправил ревьюдоги)

2024-05-20 04:52 UTC, galinabykova commented
> Очень тяжело архитектуру продумывать, вроде приходит крутая идея, а пока пытаешься её реализовать, приходиться вставлять всё новые и новые костыли, в итоге получается фигня.

Это правда, постоянно так происходит(

2024-05-20 04:53 UTC, galinabykova approved these changes

2024-05-21 04:40 UTC, merged