Task_1_1_2
IgorShal/OOP pull request #5
Opened 2023-09-21 09:10 UTC by IgorShal

2023-09-21 11:23 UTC, galinabykova requested changes

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equal(Polynomial p2) {
у любого объекта в Java есть метод для сравнения. Его лучше переопределять, чтобы по умолчанию алгоритмы могли сравнивать объекты твоего класса правильно.
https://www.examclouds.com/ru/java/java-core-russian/method-equals

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equal(Polynomial p2) {
https://javarush.com/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/test/java/SampleTest.java
у тебя практически везде по одному тесту на каждую операцию. Хочется больше. Не будет ли проблем при суммировании с полиномом 0 степени, при вычитании самого себя, при умножении на 0

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    private final int length;
значение в length отличается от coefs.length?

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public String toString() {
есть аннотация для переопределённых методов, которая служит предупреждением для компилятора, чтобы он проверил, является ли этот метод действительно переопределением

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/test/java/SampleTest.java
> +        Assertions.assertEquals(p1.differentiate(50).toString(), "0.0");
лучше сравнивать полиномы, не строчки

2023-09-21 11:23 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        coefs = arr;
напиши такой тест:
1. создаём массив coef = {1, 2, 3}
2. создаём полином p с коэффициентами coef
3. меняем coef[0]
4. сравниваем p с полиномом с коэффициентами 1, 2, 3
Ожидаемое ли это поведение?

2023-09-22 02:28 UTC, IgorShal commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    private final int length;
Нет

2023-09-22 02:28 UTC, IgorShal commented on Task_1_1_2/src/test/java/SampleTest.java
> +        Assertions.assertEquals(p1.differentiate(50).toString(), "0.0");
Понял

2023-09-23 05:44 UTC, IgorShal commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equal(Polynomial p2) {
Спасибо, исправлю

2023-09-27 03:36 UTC, galinabykova requested changes

2023-09-27 03:36 UTC, galinabykova commented on Task_1_1_2/src/test/java/SampleTest.java
> +        Polynomial.main(new String[]{null});
в этой задаче ты должен пройти порог по покрытию без этого теста

2023-09-27 03:36 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        coefs = arr;
мой косяк, нужен массив double {1.0, 2.0, 3.0}, чтобы этот конструктор вызвался

2023-09-27 03:36 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        Polynomial p2 = (Polynomial) o;
а если объект не полином?

2023-09-27 03:36 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    public boolean equals(Object o) {
вместе с equals нужно переопределять hashCode https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-09-27 03:36 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        String result = "";
здесь лучше использовать StringBuilder и в конце конвертить его в строчку
https://divancoder.ru/2017/06/string-stringbuffer-stringbuilder/#:~:text=%D0%98%D1%82%D0%B0%D0%BA%2C%20%D0%BF%D0%BE%D0%B4%D1%8B%D1%82%D0%BE%D0%B6%D0%B8%D0%BC%3A,%D0%B2%D1%8B%D1%81%D0%BE%D0%BA%D0%BE%D0%B9%20%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C%D1%8E%2C%20%D0%BD%D0%BE%20%D0%B1%D0%B5%D0%B7%20%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.

2023-09-27 05:01 UTC, galinabykova requested changes

2023-09-27 05:01 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +        if (getClass() != o.getClass()) {
а если o null?

2023-09-27 05:01 UTC, galinabykova commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    private final int length;
нужно ли тогда хранить length отдельно?

2023-09-27 05:14 UTC, IgorShal commented on Task_1_1_2/src/main/java/org/example/Polynomial.java
> +    private final int length;
Можно не хранить, но мне кажется, что в каких-то ситуация намного удобнее у полинома узнать длину через атрибут length, чем писать this.coefs.length

2023-09-27 05:40 UTC, galinabykova requested changes

2023-09-27 05:40 UTC, galinabykova commented on Task_1_1_2/src/test/java/SampleTest.java
> +        Polynomial.main(new String[]{null});
удали этот тест, пожалуйста, и если покрытие будет меньше порога, допиши тесты

2023-09-27 07:22 UTC, galinabykova requested changes
исправь ещё предупреждения от reviewdog)

2023-09-27 09:46 UTC, galinabykova approved these changes

2023-09-27 16:51 UTC, merged