Task_1_2_1
IgorShal/OOP pull request #6
Opened 2023-10-11 10:02 UTC by IgorShal

2023-10-11 17:26 UTC, galinabykova requested changes
reviewdog

2023-10-11 17:26 UTC, galinabykova commented on Task_1_1_1/.idea/misc.xml
кажется, эти файлики попали случайно

2023-10-11 17:26 UTC, galinabykova commented on Task_1_1_2/.idea/workspace.xml
и этот файлик тоже случайно попал

2023-10-11 17:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
почему ты решил итерироваться по дереву

2023-10-11 17:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    final int iteratorType;
интересное решение с типом итератора. В таком случае тебе стоит сделать Enum вместо магических констант. Это сделает твой код читаемее, не нужно будет держать в голове, что 1 - это dfs

2023-10-11 17:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    final int iteratorType;
мне кажется, не очень хорошее решение, что тип итератора нельзя менять. Получается, что пользователь не может проитерироваться по одному дереву разными обходами. Но это не противоречит условию, так что не надо менять

2023-10-11 17:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +        this.father.sons.remove(this);
что произойдёт, если мы попытаемся удалить что-то при итерировании?

2023-10-11 17:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +     * Сравниваем.
хочется тут более подробную спецификацию, что в твоём случае - равные деревья

2023-10-16 08:18 UTC, IgorShal commented on Task_1_1_2/.idea/workspace.xml
Ой

2023-10-16 08:18 UTC, IgorShal commented on Task_1_1_1/.idea/misc.xml
Ой

2023-10-16 12:08 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
Мне кажется, так намного удобнее, потому что мы получим массив поддеревьев, с которым сможем работать, как хотим, а не массив значений вершин.

2023-10-16 13:07 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +     * Сравниваем.
Написал

2023-10-16 13:07 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +        this.father.sons.remove(this);
Добавил обработку CME.

2023-10-16 13:07 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    final int iteratorType;
Согласен.

2023-10-16 13:08 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    final int iteratorType;
Хорошо.

2023-10-16 15:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    static int isIterationFlag;
кажется эта переменная принимает только значения 0 и 1. Может быть сделать boolean?

2023-10-16 15:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
не может ли доступ к поддеревьям поломать обработку CME?

2023-10-16 16:49 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    static int isIterationFlag;
Поменял

2023-10-16 16:51 UTC, IgorShal commented
Теперь не может. Потому что теперь при итерировании я помечаю все задействованные вершины как итерированные isIterationFlag, и при их изменении или изменении их поддеревьев вызывается CME

2023-10-16 19:47 UTC, galinabykova requested changes

2023-10-16 19:47 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
в любом случае не надо в толкать в дженерик raw type. Это как минимум не позволит IDE проверить всякие ошибки с типами. Надо Iterable < Tree < T >>

2023-10-16 19:47 UTC, galinabykova commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
https://javarush.com/groups/posts/2315-stiranie-tipov

2023-10-16 19:47 UTC, galinabykova commented on Task_1_1_1/.idea/misc.xml
удали эти файлики

2023-10-17 01:12 UTC, IgorShal commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<Tree> {
Понял,исправил,спасибо)

2023-10-17 03:39 UTC, galinabykova requested changes

2023-10-17 03:39 UTC, galinabykova commented on Task_1_1_1/.idea/misc.xml
удали эти файлики

2023-10-17 03:39 UTC, galinabykova commented on Task_1_1_1/.idea/misc.xml
все ненужные файлики

2023-10-17 04:45 UTC, galinabykova requested changes

2023-10-17 04:45 UTC, galinabykova commented on Task_1_1_1/src/main/java/org/example/Solution.class
это тоже надо удалить

2023-10-17 05:19 UTC, galinabykova approved these changes

2023-10-17 05:36 UTC, merged