Task_1_2_2
IgorShal/OOP pull request #7
Opened 2023-10-22 17:08 UTC by IgorShal

2023-10-23 05:27 UTC, galinabykova requested changes

2023-10-23 05:27 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Graph.java
> +public class Graph<T, E extends Number> {
Нужно разделить реализации представлений графов. Реализация алгоритма, например, Форда-Беллмана, у тебя должна быть всего одна. Подробнее напишу в телеграмм

2023-10-29 06:14 UTC, galinabykova requested changes

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Vertex.java
> +    public T value;
не стоит предоставлять доступ к полям класса. Используй геттеры и сеттеры.
https://javarush.com/groups/posts/1928-getterih-i-setterih

чтобы не писать много повторяющихся штук, можно использовать такую библиотечку
https://habr.com/ru/companies/piter/articles/676394/
Но с ней разбираться не требую, только если тебе самому интересно станет

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +    public Vertex<T> start;
также нужно обернуть в геттеры/сеттеры

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +    public Vertex<T> end;
также нужно обернуть в геттеры/сеттеры

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +    public E weight;
также нужно обернуть в геттеры/сеттеры

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +     * Забыл как эта штука назывется.Генератор вроде.
конструктор?

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Graph.java
> +    public void addEdge(E value, T start, T end) {
если ты создаёшь метод, который обязан переопределить наследник, ему не нужно давать никакой реализации, это должен быть абстрактный метод (тоже объявляешь его с ключевым словом abstract). Так ты скажешь тому, кто пишет наследника, что он обязан переопределить этот класс или этот наследник тоже будет абстрактным классом

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/AlGraph.java
> +    public ArrayList<ArrayList<Edge<T, E>>> adjacencyList;
поле не публичное должно быть

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/AmGraph.java
> +    public ArrayList<ArrayList<E>> adjacencyMatrix;
поле не публичное должно быть

2023-10-29 06:14 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/ImGraph.java
> +    public ArrayList<ArrayList<Number>> incidenceMatrix;
поле должно быть не публичным

2023-10-29 12:43 UTC, IgorShal commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +     * Забыл как эта штука назывется.Генератор вроде.
ТОЧНО

2023-10-29 12:44 UTC, IgorShal commented on Task_1_2_2/src/main/java/org/example/graph/Edge.java
> +     * Забыл как эта штука назывется.Генератор вроде.
Спасибо))

2023-10-30 08:22 UTC, IgorShal commented on Task_1_2_2/src/main/java/org/example/graph/Vertex.java
> +    public T value;
Спасибо

2023-10-30 08:26 UTC, vlasival requested changes
GG

2023-10-30 12:46 UTC, galinabykova requested changes
reviewdog

2023-10-30 12:46 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Graph.java
> +    public int getVertex(T value) {
мне кажется, что не совсем интуитивно понятно, что getVertex возвращает индекс. Я бы сделала два отдельных метода: один взять вершину для пользователя и другой, взять индекс, может быть, видный только нам и наследникам

2023-10-30 12:46 UTC, galinabykova commented on Task_1_2_2/src/main/java/org/example/graph/Graph.java
> +            throw new IOException("Error");
неинформативное сообщение об ошибке

2023-10-30 14:38 UTC, vlasival requested changes
Исправь мои замечания, раз я ревьюер теперь.

2023-10-30 14:38 UTC, vlasival commented on Task_1_2_2/src/main/java/org/example/Main.java
> +import org.example.graph.AlGraph;
Зачем отступ перед `импортом`?

2023-10-30 14:38 UTC, vlasival commented on Task_1_2_2/src/main/java/org/example/graph/AmGraph.java
> +            if (edge.getStart().getValue() == value ||
Перенос строки нормальный сделай

2023-10-30 14:38 UTC, vlasival commented on Task_1_2_2/src/main/java/org/example/graph/Graph.java
> +    public void setEdges(E weight, T start, T end, E newWeight, T newStart, T newEnd) {
Ставь перегруженные методы друг за другом. Иначе это **_violation_**

2023-10-31 06:11 UTC, galinabykova approved these changes

2023-10-31 06:14 UTC, galinabykova commented
Ой, забыла покрытие посмотреть(

2023-10-31 12:50 UTC, merged

2023-10-31 12:51 UTC, vlasival reviewed
jj