Task_1_4_1
IgorShal/OOP pull request #9
Opened 2023-11-18 16:33 UTC by IgorShal

2023-11-18 18:01 UTC, galinabykova requested changes

2023-11-18 18:01 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        if (mark < 0 || mark > 5) {
а 0 задумывался как корректная оценка?)

2023-11-18 18:01 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +            this.marks.get(semester).put(lesson, new ArrayList<>());
получается, что в семесте по одному предмету можно получить много оценок? почему так?

2023-11-18 18:01 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        if (mark < 0 || mark > 5) {
Кстати, в универе оценки "зачет", "хорошо", "отлично". Если сделать оценку Enum, сюда нельзя будет так просто затолкать число, большее 5

2023-11-18 18:01 UTC, galinabykova commented on Task_1_4_1/src/test/java/CreditBookTest.java
> +        assertTrue(creditBook1.isDiplomaPossible());
в этом куске кода совсем непонятно, какой должен быть ответ. Было бы лучше, если у creditBook были более осмысленные названия (например, withoutThreeCreditBook)

2023-11-25 15:12 UTC, IgorShal commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        if (mark < 0 || mark > 5) {
Ой

2023-11-25 15:13 UTC, IgorShal commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        if (mark < 0 || mark > 5) {
Всё переделал

2023-11-25 15:13 UTC, IgorShal commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +            this.marks.get(semester).put(lesson, new ArrayList<>());
Крыша поехала. Теперь только одну оценку можно.

2023-11-25 15:59 UTC, IgorShal commented
Переделал всё вообще в стримы, чтобы научиться ими пользоваться).

2023-11-25 16:34 UTC, galinabykova requested changes

2023-11-25 16:34 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        markPassed("Passed"),
кажется, что тут можно делать 0, потому что эти числа используются чисто для сравнения)

2023-11-25 16:34 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +        markFive(5),
enum константа, их именуют в uppercase
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2023-11-25 16:34 UTC, galinabykova commented on Task_1_4_1/src/main/java/org/example/CreditBook.java
> +    public enum Mark {
лучше вынести в отдельный файлик

2023-11-26 08:56 UTC, galinabykova approved these changes

2023-11-26 15:03 UTC, merged